### ISSUE TITLE
Wrong/Broken UV on some parts of rig

### ISSUE THREAD

**Issue by FXVictis** [DarthLilo/ice_cube#2]
I just spawn a rig in scene with _Shift+A_, and set up my own skin. and here be a bug with UV on **_legs_**(backside) - both layers is broken(legs and they 2 layers) are mirrored by X axis. And on second layer of left **steve arm** is broken too. same problem. i see it on version **1.4.5** - **1.4.7**.
Please fix it.
![image1](https://user-images.githubusercontent.com/86255176/233808820-3035df4e-17cd-4b11-bc5d-631f064ea78b.png)
![image](https://user-images.githubusercontent.com/86255176/233808812-0228936d-680f-443b-af40-3dcfbd5170a3.png)

**Comment by FXVictis** [comment]
Here is how it should be.
![image](https://user-images.githubusercontent.com/86255176/233808981-87f5774e-2468-435b-a411-0be258dcf7b2.png)
![image](https://user-images.githubusercontent.com/86255176/233809018-be9b0081-1297-46e3-9fe0-4fe696229ded.png)

**Comment by DarthLilo** [comment]
Looked into it, confirmed, and patched, I'll send out a 1.4.8 update later to address this but until then you can re-download the source code.
